### ISSUE TITLE
BottomSheetBehavior error

### ISSUE THREAD

**Issue by amirsarafian** [ZarinPal/Android-SDK#11]
**Describe the bug**
BottomSheetBehavior error in LauncherActivity
![Capture](https://user-images.githubusercontent.com/22930592/163707694-6fbfcbc2-c6f5-4f7b-b7fd-67c6d7aef725.PNG)

**Information**
- Android OS Version: 22
- Library Version: 0.5.3

**Comment by ImanX** [comment]
@amirsarafian Can you describe it?
