### ISSUE TITLE
Callback 

### ISSUE THREAD

**Issue by skhanbeiki** [ZarinPal/Android-SDK#14]
Callback URL: A valid URI or URL Address for sending result purchase.
نمیخوام برگرده به وب ، میخواییم برگرده به خود اپ - و اونجا نتیجه پرداخت رو بگیریم .
خودتون صفحه وب پیشفرض ندارین ، که بره اون داخل و اون صفحه ارسالش کنه به اپ ما ؟

**Comment by amirsarafian** [comment]
متاسفانه پس از پرداخت موفقیت آمیز به صورت خودکار به اپلیکیشن باز نمی گرده
گوشی: note 8 pro شیاِیومی
نسخه اندروید: 11
ممنون میشم بررسی و رفع کنید

**Comment by ImanX** [comment]
> Callback URL: A valid URI or URL Address for sending result purchase. نمیخوام برگرده به وب ، میخواییم برگرده به خود اپ - و اونجا نتیجه پرداخت رو بگیریم . خودتون صفحه وب پیشفرض ندارین ، که بره اون داخل و اون صفحه ارسالش کنه به اپ ما ؟

That's better You define a deeplink of your app.
