### ISSUE TITLE
دریافت شماره تلفن بعد از انجام خرید

### ISSUE THREAD

**Issue by Alireza-Jamali** [ZarinPal/Android-SDK#15]
بعد از انجام
client.launchBillingFlow
و گرفتن موفقیت آمیز
Receipt receipt = task.getSuccess();
هیچ اطلاعاتی در مورد شماره تلفن وارد شده کاربر در دسترس نیست
purchase.toSerialize();
هم چک کردم فقط کد محصول هست و بقیه اطلاعات محصول
امکانش هست شماره تلفنی که کاربر قبل از ورود به صفحه بانک وارد کرده رو، بعد از خرید دریافت کرد؟

**Comment by ImanX** [comment]
سلام
متاسفانه همچین قابلیتی رو sdk درحال حاضر نداره، اما شما میتونید از همون موبایل و ایمیل که کاربرتون وارد کرده زمانی که تراکنشت موفق بود استفاده کنید، در آینده همچین فیچری رو پیاده خواهیم کرد.
