### ISSUE TITLE
نصب کتابخانه

### ISSUE THREAD

**Issue by Mohamadrj74** [ZarinPal/Android-SDK#16]
سلام من قسمت اولی که گفتید اضافه کنیم 
            ext.zarinpalSdkVersion = (LATEST_VERSION_REALEASE) //inform of Releases: https://github.com/ZarinPal/Android-SDK/releases
   در آپدیت جدید اندروید استادیو جایی به نام all project  ندارم 
دقیقا کجا باید بنویسم این کد رو 
و آیا جای zarinpalSdkVersion چیز دیگه ای باید بنویسم ؟؟

**Comment by ImanX** [comment]
Hey @Mohamadrj74 You must define last version that you find any version in Tags of repo.
Thank you.
