### ISSUE TITLE
بازگشت به اپ بعد از خرید

### ISSUE THREAD

**Issue by mbasirzadeh** [ZarinPal/Android-SDK#19]
سلام  من تو پروژه ام از معماری mvvm استفاده کردم
و  launchbillingflow رو توی View Model  نوشتم .توی یکی از فرگمنت هام.و اینکه بعد از خرید هم url call back  رو به سمت سایتی نمیزنم و میخوام وارد برنامه شم پس براش توی منیفست schema رو تعریف کردم . منتهی بعد از پرداخت موفق توسط کاربر وقتی دکمه برگشت به صفحه پذیرنده رو میزنه  دیگه متد onComplete صدا زده نمیشه که اپ بفهمه خرید انجام شده و کاراش رو جلو ببره.به عبارتی اپ دوباره create میشه و برنمیگرده به همون فرگمنتم که کارای بعد خرید رو ببرم جلو .متد onComplete وقتی صدا زده میشه که بعد پرداخت موفق  بعدش کاربر دکمه back رو بزنه نه برگشت به صفحه پذیرنده.

**Comment by mbasirzadeh** [comment]
از نسخه 0.6.0 استفاده میکنم

**Comment by mbasirzadeh** [comment]
چجوری پرداخت رو پیاده کنم که وقتی میخوام برگردم به اپلیکیشن متد onComplete کال بشه و خرید کاربرو  تکمیل کنم تو برنامم؟

**Comment by ImanX** [comment]
Fixed it.
https://github.com/ZarinPal/Android-SDK/releases/tag/0.6.1
