### ISSUE TITLE
ClientState error state

### ISSUE THREAD

**Issue by SudoDios** [ZarinPal/Android-SDK#22]
HI.
What is the error (no code or expl) ?

**Comment by ImanX** [comment]
We need more information about it. please sharing.

**Comment by SudoDios** [comment]
I executed the [sample](https://github.com/ZarinPal/Android-SDK/blob/master/Sample/app/src/main/java/com/zarinpal/sample/inappbilling/MainActivity.kt) code exactly and changed the MERCHANT ID code.  
But this error has neither a code nor an explanation.

**Comment by ImanX** [comment]
We can't help you if you don't have any information.

**Comment by SudoDios** [comment]
I will send it to you tomorrow
