### ISSUE TITLE
can't open Payment gateway

### ISSUE THREAD

**Issue by sajjad32156** [ZarinPal/Android-SDK#6]
this is my android studio manifest :
![Capture](https://user-images.githubusercontent.com/93077574/138590338-a6096c60-ed74-4929-bfe1-2b8d2b80c036.JPG)

and my Fragment code :
![Capture2](https://user-images.githubusercontent.com/93077574/138590361-b88d81ef-5578-461e-bb44-6ac8199afae9.JPG)

I have also received requisites such as internet access but these codes do not work and only show the price.
When I apply for payment, only Progress is displayed and it gets stuck at this stage :

![Screenshot_۲۰۲۱۱۰۲۳-۱۷۲۳۰۲_MiniProject](https://user-images.githubusercontent.com/93077574/138590898-139bfeb9-3af7-485d-8862-7d5b645caf8b.jpg)
![Screenshot_۲۰۲۱۱۰۲۳-۱۷۲۳۱۳_MiniProject](https://user-images.githubusercontent.com/93077574/138590900-0165bada-b119-4e94-b690-60163413fd76.jpg)

**Comment by ImanX** [comment]
Dear @sajjad32156 
What's your android version?

**Comment by sajjad32156** [comment]
@ImanX  
Android 10

**Comment by ImanX** [comment]
@sajjad32156 OK, define `android:usesCleartextTraffic="true"` in `manifest.xml` and announce the result to me.
